#!/usr/bin/env python3
"""Regenerate tests/golden.json.

The golden file pins the numbers the paper actually prints.  It is generated
from the code, so it certifies nothing on its own -- what it does is make any
later change to those numbers visible and deliberate.  Regenerate it only when
a change to them has been argued for, and say so in the commit message.

    python3 tests/make_golden.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import slogpet as sp
from slogpet.data import load_systems, load_detector_groups

HERE = os.path.dirname(os.path.abspath(__file__))
F_OS = (5.0, 10.0)
D_CYLS = (200.0, 300.0)
SCAN_LENGTHS = (200.0, 500.0, 1000.0, 1800.0)


def build():
    out = {"_comment": [
        "Generated by tests/make_golden.py -- do not edit by hand.",
        "These are the numbers the paper prints.  A change here is a change to",
        "the paper and must be argued for, not absorbed."]}

    out["systems"] = {}
    for sc in load_systems():
        key = f"{sc.name} L={sc.L_pet:.0f} MRD={sc.L_mrd:.0f}"
        out["systems"][key] = {
            "S_ideal": sc.S_ideal(),
            "epsilon": sc.efficiency(),
            "r": {f"{F_o:g}": sc.r(sp.Task(F_o, 300.0)) for F_o in F_OS},
        }

    out["designs"] = {}
    for g in load_detector_groups():
        out["designs"][g.id] = {
            f"r_Fo{F_o:g}_D{D:g}": g.scanners[0].r(sp.Task(F_o, D))
            for F_o in F_OS for D in D_CYLS}

    out["protocols"] = {}
    for L_pet in (300.0, 1000.0, 1500.0):
        sc = sp.Scanner("generic", L_pet, 740.0, 3.4, 3.8, F_t=32.0, epsilon=1.0)
        for D_cyl in D_CYLS:
            prof = sp.axial_profile(sc, D_cyl)
            for S in SCAN_LENGTHS:
                p = sp.optimal_protocol(prof, S)
                out["protocols"][f"L={L_pet:.0f} D={D_cyl:.0f} S={S:.0f}"] = {
                    "n_beds": p.n_beds, "spacing": p.spacing, "min_eta": p.min_eta}

    out["snr2"] = {}
    for g in load_detector_groups():
        for sc, _style in g.configurations:
            for F_o in F_OS:
                for D_cyl in D_CYLS:
                    task = sp.Task(F_o, D_cyl)
                    for S in SCAN_LENGTHS:
                        key = (f"{g.id} L={sc.L_pet:.0f} MRD={sc.L_mrd:.0f} "
                               f"Fo={F_o:g} D={D_cyl:g} S={S:g}")
                        out["snr2"][key] = sp.snr2(sc, task, S).snr2_min
    return out


if __name__ == "__main__":
    doc = build()
    path = os.path.join(HERE, "golden.json")
    with open(path, "w") as fh:
        json.dump(doc, fh, indent=1, sort_keys=False)
        fh.write("\n")
    n = (len(doc["systems"]) * 4 + len(doc["designs"]) * 4
         + len(doc["protocols"]) * 3 + len(doc["snr2"]))
    print("wrote %s: %d pinned numbers" % (path, n))
